project:
  type: book
  output-dir: docs

book:
  title: "Alcohol consumption per country"
  author: "Minya, Emilio, Ambre, Franck & Perrine"
  date: "12/05/2025"
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/Reveal_your_country.qmd
    - chapters/summary.qmd

format:
  html:
    theme: [cosmo, styles/style.scss]



